Update details.md
lukeocodes/hacktoberfest-checker pull request #135
Opened 2020-10-31 11:10 UTC by Nigar6001

# Pull Request

## Description:

## Related Issue:

Closes #XXXXX

2020-10-31 13:56 UTC, Nigar6001 commented
Hello. I have made some updates to Update details.md file. If you think it is eligible to be merged, please accept it and merge.

2020-10-31 17:30 UTC, lukeocodes requested changes
thanks for your contribution :) please see some requested changes

2020-10-31 17:30 UTC, lukeocodes commented on content/ru/details.md
> +[Английская версия этого файла details.md](https://github.com/lukeocodes/hacktoberfest-checker/blob/main/content/en/details.md)
please dont add additional content because it might not reflect the other translations

2020-10-31 17:30 UTC, lukeocodes commented on content/ru/details.md
> +Oписание: "Hacktoberfest Ninja - Checker - Hacktoberfest представлен DigitalOcean"
we shouldn't change the key names

2020-11-01 09:35 UTC, lukeocodes commented on content/ru/details.md
> +Oписание: "Hacktoberfest Ninja - Checker - Hacktoberfest представлен DigitalOcean"
```suggestion
title: "Hacktoberfest Ninja - Checker"
description: "Hacktoberfest Ninja - Checker - Hacktoberfest представлен DigitalOcean"
```

2020-11-01 09:35 UTC, lukeocodes approved these changes

2020-11-01 09:35 UTC, merged